# Colour Picker

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
plt.style.use('default')

import matplotlib
matplotlib.use('TkAgg')  # 强制使用 TkAgg

import pyperclip
import random
import glob

import os
dp = os.environ.get('pub_data')
data = dp + 'birds/'

In [39]:
# Dataset
img_path = glob.glob(data + '*.jpg')
print(len(img_path))

21


In [40]:
# Example images
fig, ax = plt.subplots(2, 4, figsize=(20, 10))

count = 0
for i in range(2):
    for j in range(4):
        img = mpimg.imread(img_path[count])

        ax[i, j].imshow(img)
        ax[i, j].axis('off')
        ax[i, j].axis('tight')
        ax[i, j].axis('image')

        count+=1

## Colour picker 1

In [41]:
def onclick(event):
    global img

    # get x, y of click
    x = round(event.xdata)
    y = round(event.ydata)

    # Get RGB values
    rgb = img[y][x]

    # save to clip board
    pyperclip.copy(str(rgb))

In [42]:
global img

fig = plt.figure(figsize=(5,5))

# Load image and add count
path = img_path[-1]
img = mpimg.imread(path)

# Add an interactive widget to figure
cid = fig.canvas.mpl_connect('button_press_event', onclick)
plt.imshow(img)
plt.show()

## Colour picker 2 

In [44]:
def onclick(event):
    global img
    global rgb
    
    # get x,y of click
    x = round(event.xdata)
    y = round(event.ydata)
    
    # get RGB values
    rgb = img[y][x]
    
    #Update second plot with colour
    change_choice()

In [45]:
def onpress(event):
    global rgb
    global colours
    
    #Get key 
    key = event.key

    if key == 'n':
        change_image()
        
    elif key == 'c':
         # save to clip board
        pyperclip.copy(str(rgb))
        
        # add to list of colours
        colours.append(rgb)
        
        change_choice()

In [46]:
def change_image():
    global img_path
    global img
    global ax
    global rgb
    
    # close all open plots
    plt.close('all')
    
    fig,ax = plt.subplots(1,2,figsize=(10,5))
    
    # add an interactive widget to figure 
    cid = fig.canvas.mpl_connect('button_press_event', onclick)
    cid2 = fig.canvas.mpl_connect('key_press_event', onpress)

    # load random image
    path = random.choice(img_path)
    img = mpimg.imread(path)
    
    ax[0].imshow(img)
    
    # reset the colour window
    rgb = [255,255,255]
    change_choice()


In [47]:
def change_choice():
    global img
    global ax
    global colours
    global rgb
    
    # remove previous count
    for txt in ax[1].texts:
        txt.set_visible(False)
    
    # create array of colour choice
    dims = np.shape(img)
    col = np.array([[rgb]*dims[0]]*dims[1])
    ax[1].imshow(col)
    
    # update colour count
    ax[1].text(0, 15, len(colours),color='r',size=20)
    
    plt.show()

In [54]:
%matplotlib tk
global img_path
global colours
colours = []

# load image paths
img_path = glob.glob(data + "*.jpg")

# start widget
change_image()

In [53]:
colours

[array([242,  98,  45], dtype=uint8),
 array([1, 1, 1], dtype=uint8),
 array([  3,  47, 136], dtype=uint8),
 array([129, 142,  70], dtype=uint8),
 array([251, 120,   2], dtype=uint8),
 array([161,  86, 106], dtype=uint8)]